---

- name: Download node
  get_url:
    url: https://deb.nodesource.com/setup_4.x
    dest: /services/temp/setup_node.sh
    mode: 0755

- name: Setup node
  shell: /services/temp/setup_node.sh

- name: Install node
  apt:
    name: nodejs
    state: present

- name: Install node packages dependency
  apt:
    name: build-essential
    update_cache: yes
    state: present

- name: Ensure update to npm 3
  npm:
    name: npm@3
    global: yes
    state: present

- name: Install aurelia cli globally using npm
  npm:
    name: aurelia-cli
    global: yes
    state: present

- name: Install all packages except optional
  shell: npm install --no-optional
  args:
    chdir: /services/CorpWeb/
  ignore_errors: yes

- name: Run aurelia-materialize-bridge script
  shell: ./node_modules/.bin/r.js -o rbuild.js
  args:
    chdir: /services/CorpWeb

- name: Install aurelia-materialize-bridge
  shell: npm install aurelia-materialize-bridge
  args:
    chdir: /services/CorpWeb/

- name: Install aurelia-validation
  shell: npm install aurelia-validation
  args:
    chdir: /services/CorpWeb/