---
EVE_CLIENT_ID: CREST
EVE_SECRET_KEY: CREST_SECRET
DEFAULT_HOST: alpha.corpweb.com
API_VIRTUAL_HOST: api.corpweb.com
SIGN_SECRET: RANDOM_STRING
NAME: CHARACTER_NAME
CORPORATION_ID: 98117593
ALLIANCE_ID: 99004905
DOMAIN_EMAIL: example@corpweb.com