---
EVE_CLIENT_ID: CREST
EVE_SECRET_KEY: CREST_SECRET
DEFAULT_HOST: alpha.corpweb.com
API_VIRTUAL_HOST: api.corpweb.com
SIGN_SECRET: RANDOM_STRING
NAME: CHARACTER_NAME
SUPER_ADMIN_ID: 379808692
SUPER_DEV_ID: 93256039
DOMAIN_EMAIL: example@corpweb.com
SSL_TEST: True