---

- name: Bundle CorpWeb
  shell: au build --env prod
  args:
    chdir: /services/CorpWeb

- name: Prepare certificates directory
  file:
    path: /services/certificates
    state: directory

- name: Stop LetEncrypt Certificate Handler Container
  docker_container:
    name: corpweb-ssl
    image: jrcs/letsencrypt-nginx-proxy-companion
    state: stopped
    keep_volumes: True

- name: Ensure CorpWeb container does not exist
  docker_container:
    name: corpweb-dashboard
    state: absent
    keep_volumes: False

- name: Ensure CorpWeb API container does not exist
  docker_container:
    name: corpweb-api
    state: absent
    keep_volumes: False

- name: Ensure old CorpWeb image does not exist
  docker_image:
    name: corpweb
    state: absent

- name: Build CorpWeb Image
  docker_image:
    name: corpweb
    state: present
    path: /services/CorpWeb
    pull: False

- name: Ensure old CorpWeb API image does not exist
  docker_image:
    name: corpweb-api
    state: absent

- name: Build CorpWebAPI Image
  docker_image:
    name: corpweb-api
    state: present
    path: /services/CorpWebAPI
    pull: False

- name: Start CorpWeb Container
  docker_container:
    name: corpweb-dashboard
    image: corpweb
    state: started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/usr/share/nginx/html"
      - "/etc/nginx/vhost.d"
      - "/services/certificates:/etc/nginx/certs:ro"
    env:
      DEFAULT_HOST: "{{ DEFAULT_HOST }}"

- name: Start LetsEncrypt Certificate Handler Container
  docker_container:
    name: corpweb-ssl
    image: jrcs/letsencrypt-nginx-proxy-companion
    state: started
    volumes:
      - "/services/certificates:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - corpweb-dashboard
    env:
      ACME_CA_URI: "https://acme-staging.api.letsencrypt.org/directory"

- name: Create default cert symlink
  file:
    src: ./{{ DEFAULT_HOST }}/fullchain.pem
    dest: /services/certificates/default.crt
    state: link
    force: yes

- name: Create default key symlink
  file:
    src: ./{{ DEFAULT_HOST }}/key.pem
    dest: /services/certificates/default.key
    state: link
    force: yes

- name: Wait for Nginx
  uri:
    url: http://127.0.0.1
  register: nginx_wait
  until: nginx_wait.status == 200
  retries: 12
  delay: 5
  ignore_errors: true

- name: Start Rethinkdb Container
  docker_container:
    name: corpweb-db
    image: rethinkdb
    state: started
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:28015:28015"

- name: Wait for Rethinkdb web admin
  uri:
    url: http://127.0.0.1:8080
  register: rethinkdb_wait
  until: rethinkdb_wait.status == 200
  retries: 12
  delay: 5
  ignore_errors: true

- name: Start CorpWebAPI Container
  docker_container:
    name: corpweb-api
    image: corpweb-api
    state: started
    links:
      - "corpweb-db:db"
    env_file: /services/CorpWebAPI/env

- name: Wait for CorpWeb API
  uri:
    url: http://{{ API_VIRTUAL_HOST }}
  register: corpwebapi_wait
  until: corpwebapi_wait.status == 200
  retries: 12
  delay: 5
  ignore_errors: true
  tags:
    - wait
