---

- name: Install Galaxy Dependencies
  local_action: command ansible-galaxy install -r requirements.yml --ignore-errors

- name: Create working directory
  file:
    path: /services/temp
    state: directory
    recurse: yes

- name: RethinkDB tools install (Add apt repo)
  raw: source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list

- name: Rethinkdb tools install (Download gpg key)
  raw: wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -

- name: RethinkDB tools install (apt)
  apt:
    name: rethinkdb
    update_cache: yes
    state: present

- name: Install rethinkdb python driver
  pip:
    name: rethinkdb

- name: Check Swapfile
  stat:
    path: /services/temp/swapfile
  register: swapfile_check

- name: Create Swapfile (if doesn't exist)
  shell: fallocate -l 2G /services/temp/swapfile
  when: swapfile_check.stat.exists == False

- name: Protect Swapfile (if doesn't exist)
  file:
    path: /services/temp/swapfile
    mode: 0600
  when: swapfile_check.stat.exists == False

- name: Transform Swapfile (if doesn't exist)
  shell: mkswap /services/temp/swapfile
  when: swapfile_check.stat.exists == False

- name: Activate Swapfile (if doesn't exist)
  shell: swapon /services/temp/swapfile
  when: swapfile_check.stat.exists == False
